# This is just data entry, where are you retrieving students with lowestr and highest score, where are he subjects?

# student's biography
print("STUDENT'S BIOGRAPHY")
students_list = []
n = int(input("enter the student list:"))
print("\n")
for i in range(0, n):
    name = str(input("enter student's name:"))
    students_list.append(name)
    registration_number = str(input("enter student's registration_number:"))
    students_list.append(registration_number)
    age = str(input("enter student's age:"))
    students_list.append(age)
    nationality = str(input("enter student's nationality:"))
    students_list.append(nationality)
    phone_number = str(input("enter student's phone number:"))
    students_list.append(phone_number)
    batch_year = str(input("enter student's batch year:"))
    students_list.append(batch_year)
    course = str(input("enter student's course:"))
    students_list.append(course)
    program = str(input("enter student's program admitted in:"))
    students_list.append(program)
    graduation_year = str(input("enter the expected year of graduation:"))
    students_list.append(graduation_year)
    print("\n")
print("student name:{name}")
print("student registration number:{registration_number}")
print("student age:{age}")
print("student nationality:{nationality}")
print("student phone_number:{phone_number}")
print("student batch_year:{batch_year}")
print("student course:{course}")
print("student admitted program:{program}")
print("student graduation_year:{graduation_year}")
